/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CourierDetails} from './CourierDetails';

/**
 * The Courier model module.
 * @module model/Courier
 * @version 3.0
 */
export class Courier {
  /**
   * Constructs a new <code>Courier</code>.
   * @alias module:model/Courier
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Courier</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Courier} obj Optional instance to populate.
   * @return {module:model/Courier} The populated <code>Courier</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Courier();
      if (data.hasOwnProperty('pickupDetails'))
        obj.pickupDetails = CourierDetails.constructFromObject(data['pickupDetails']);
      if (data.hasOwnProperty('deliveryDetails'))
        obj.deliveryDetails = CourierDetails.constructFromObject(data['deliveryDetails']);
    }
    return obj;
  }
}

/**
 * @member {module:model/CourierDetails} pickupDetails
 */
Courier.prototype.pickupDetails = undefined;

/**
 * @member {module:model/CourierDetails} deliveryDetails
 */
Courier.prototype.deliveryDetails = undefined;

