/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressLabel} from './AddressLabel';
import {DatingLabel} from './DatingLabel';
import {Fulfillment} from './Fulfillment';
import {Location} from './Location';
import {ModelPackage} from './ModelPackage';
import {Price} from './Price';
import {ShippingFees} from './ShippingFees';
import {Tax} from './Tax';

/**
 * The CreateListingRequest model module.
 * @module model/CreateListingRequest
 * @version 3.0
 */
export class CreateListingRequest {
  /**
   * Constructs a new <code>CreateListingRequest</code>.
   * @alias module:model/CreateListingRequest
   * @class
   * @param productId {String} 
   * @param price {module:model/Price} 
   * @param tax {module:model/Tax} 
   * @param listingStatus {module:model/CreateListingRequest.ListingStatusEnum} 
   * @param fulfillmentProfile {module:model/CreateListingRequest.FulfillmentProfileEnum} 
   * @param packages {Array.<module:model/ModelPackage>} 
   * @param locations {Array.<module:model/Location>} 
   */
  constructor(productId, price, tax, listingStatus, fulfillmentProfile, packages, locations) {
    this.productId = productId;
    this.price = price;
    this.tax = tax;
    this.listingStatus = listingStatus;
    this.fulfillmentProfile = fulfillmentProfile;
    this.packages = packages;
    this.locations = locations;
  }

  /**
   * Constructs a <code>CreateListingRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateListingRequest} obj Optional instance to populate.
   * @return {module:model/CreateListingRequest} The populated <code>CreateListingRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateListingRequest();
      if (data.hasOwnProperty('product_id'))
        obj.productId = ApiClient.convertToType(data['product_id'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = Price.constructFromObject(data['price']);
      if (data.hasOwnProperty('tax'))
        obj.tax = Tax.constructFromObject(data['tax']);
      if (data.hasOwnProperty('listing_status'))
        obj.listingStatus = ApiClient.convertToType(data['listing_status'], 'String');
      if (data.hasOwnProperty('shipping_fees'))
        obj.shippingFees = ShippingFees.constructFromObject(data['shipping_fees']);
      if (data.hasOwnProperty('subsidized_shipping'))
        obj.subsidizedShipping = ApiClient.convertToType(data['subsidized_shipping'], 'Boolean');
      if (data.hasOwnProperty('fulfillment_profile'))
        obj.fulfillmentProfile = ApiClient.convertToType(data['fulfillment_profile'], 'String');
      if (data.hasOwnProperty('fulfillment'))
        obj.fulfillment = Fulfillment.constructFromObject(data['fulfillment']);
      if (data.hasOwnProperty('packages'))
        obj.packages = ApiClient.convertToType(data['packages'], [ModelPackage]);
      if (data.hasOwnProperty('locations'))
        obj.locations = ApiClient.convertToType(data['locations'], [Location]);
      if (data.hasOwnProperty('address_label'))
        obj.addressLabel = AddressLabel.constructFromObject(data['address_label']);
      if (data.hasOwnProperty('dating_label'))
        obj.datingLabel = DatingLabel.constructFromObject(data['dating_label']);
    }
    return obj;
  }
}

/**
 * @member {String} productId
 */
CreateListingRequest.prototype.productId = undefined;

/**
 * @member {module:model/Price} price
 */
CreateListingRequest.prototype.price = undefined;

/**
 * @member {module:model/Tax} tax
 */
CreateListingRequest.prototype.tax = undefined;

/**
 * Allowed values for the <code>listingStatus</code> property.
 * @enum {String}
 * @readonly
 */
CreateListingRequest.ListingStatusEnum = {
  /**
   * value: "ACTIVE"
   * @const
   */
  ACTIVE: "ACTIVE",

  /**
   * value: "INACTIVE"
   * @const
   */
  INACTIVE: "INACTIVE"
};
/**
 * @member {module:model/CreateListingRequest.ListingStatusEnum} listingStatus
 */
CreateListingRequest.prototype.listingStatus = undefined;

/**
 * @member {module:model/ShippingFees} shippingFees
 */
CreateListingRequest.prototype.shippingFees = undefined;

/**
 * @member {Boolean} subsidizedShipping
 */
CreateListingRequest.prototype.subsidizedShipping = undefined;

/**
 * Allowed values for the <code>fulfillmentProfile</code> property.
 * @enum {String}
 * @readonly
 */
CreateListingRequest.FulfillmentProfileEnum = {
  /**
   * value: "NON_FBF"
   * @const
   */
  NON_FBF: "NON_FBF",

  /**
   * value: "FBF_LITE"
   * @const
   */
  FBF_LITE: "FBF_LITE",

  /**
   * value: "FBF"
   * @const
   */
  FBF: "FBF"
};
/**
 * @member {module:model/CreateListingRequest.FulfillmentProfileEnum} fulfillmentProfile
 */
CreateListingRequest.prototype.fulfillmentProfile = undefined;

/**
 * @member {module:model/Fulfillment} fulfillment
 */
CreateListingRequest.prototype.fulfillment = undefined;

/**
 * @member {Array.<module:model/ModelPackage>} packages
 */
CreateListingRequest.prototype.packages = undefined;

/**
 * @member {Array.<module:model/Location>} locations
 */
CreateListingRequest.prototype.locations = undefined;

/**
 * @member {module:model/AddressLabel} addressLabel
 */
CreateListingRequest.prototype.addressLabel = undefined;

/**
 * @member {module:model/DatingLabel} datingLabel
 */
CreateListingRequest.prototype.datingLabel = undefined;

