/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Fulfillment model module.
 * @module model/Fulfillment
 * @version 3.0
 */
export class Fulfillment {
  /**
   * Constructs a new <code>Fulfillment</code>.
   * @alias module:model/Fulfillment
   * @class
   * @param dispatchSla {Number} 
   * @param shippingProvider {module:model/Fulfillment.ShippingProviderEnum} 
   * @param procurementType {module:model/Fulfillment.ProcurementTypeEnum} 
   */
  constructor(dispatchSla, shippingProvider, procurementType) {
    this.dispatchSla = dispatchSla;
    this.shippingProvider = shippingProvider;
    this.procurementType = procurementType;
  }

  /**
   * Constructs a <code>Fulfillment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Fulfillment} obj Optional instance to populate.
   * @return {module:model/Fulfillment} The populated <code>Fulfillment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Fulfillment();
      if (data.hasOwnProperty('dispatch_sla'))
        obj.dispatchSla = ApiClient.convertToType(data['dispatch_sla'], 'Number');
      if (data.hasOwnProperty('shipping_provider'))
        obj.shippingProvider = ApiClient.convertToType(data['shipping_provider'], 'String');
      if (data.hasOwnProperty('procurement_type'))
        obj.procurementType = ApiClient.convertToType(data['procurement_type'], 'String');
      if (data.hasOwnProperty('region_restriction'))
        obj.regionRestriction = ApiClient.convertToType(data['region_restriction'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} dispatchSla
 */
Fulfillment.prototype.dispatchSla = undefined;

/**
 * Allowed values for the <code>shippingProvider</code> property.
 * @enum {String}
 * @readonly
 */
Fulfillment.ShippingProviderEnum = {
  /**
   * value: "FLIPKART"
   * @const
   */
  FLIPKART: "FLIPKART",

  /**
   * value: "SELLER"
   * @const
   */
  SELLER: "SELLER",

  /**
   * value: "FLIPKART_SELLER"
   * @const
   */
  FLIPKART_SELLER: "FLIPKART_SELLER",

  /**
   * value: "SELLER_FLIPKART"
   * @const
   */
  SELLER_FLIPKART: "SELLER_FLIPKART"
};
/**
 * @member {module:model/Fulfillment.ShippingProviderEnum} shippingProvider
 */
Fulfillment.prototype.shippingProvider = undefined;

/**
 * Allowed values for the <code>procurementType</code> property.
 * @enum {String}
 * @readonly
 */
Fulfillment.ProcurementTypeEnum = {
  /**
   * value: "EXPRESS"
   * @const
   */
  EXPRESS: "EXPRESS",

  /**
   * value: "REGULAR"
   * @const
   */
  REGULAR: "REGULAR",

  /**
   * value: "INTERNATIONAL"
   * @const
   */
  INTERNATIONAL: "INTERNATIONAL",

  /**
   * value: "MADE_TO_ORDER"
   * @const
   */
  MADE_TO_ORDER: "MADE_TO_ORDER",

  /**
   * value: "DOMESTIC"
   * @const
   */
  DOMESTIC: "DOMESTIC"
};
/**
 * @member {module:model/Fulfillment.ProcurementTypeEnum} procurementType
 */
Fulfillment.prototype.procurementType = undefined;

/**
 * Allowed values for the <code>regionRestriction</code> property.
 * @enum {String}
 * @readonly
 */
Fulfillment.RegionRestrictionEnum = {
  /**
   * value: "zonal"
   * @const
   */
  zonal: "zonal",

  /**
   * value: "national"
   * @const
   */
  national: "national",

  /**
   * value: "none"
   * @const
   */
  none: "none"
};
/**
 * @member {module:model/Fulfillment.RegionRestrictionEnum} regionRestriction
 */
Fulfillment.prototype.regionRestriction = undefined;

