/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InvoiceItem} from './InvoiceItem';

/**
 * The InvoiceRequest model module.
 * @module model/InvoiceRequest
 * @version 3.0
 */
export class InvoiceRequest {
  /**
   * Constructs a new <code>InvoiceRequest</code>.
   * @alias module:model/InvoiceRequest
   * @class
   * @param invoiceDate {Date} 
   * @param items {Array.<module:model/InvoiceItem>} 
   */
  constructor(invoiceDate, items) {
    this.invoiceDate = invoiceDate;
    this.items = items;
  }

  /**
   * Constructs a <code>InvoiceRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InvoiceRequest} obj Optional instance to populate.
   * @return {module:model/InvoiceRequest} The populated <code>InvoiceRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InvoiceRequest();
      if (data.hasOwnProperty('invoiceNumber'))
        obj.invoiceNumber = ApiClient.convertToType(data['invoiceNumber'], 'String');
      if (data.hasOwnProperty('invoiceDate'))
        obj.invoiceDate = ApiClient.convertToType(data['invoiceDate'], 'Date');
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [InvoiceItem]);
    }
    return obj;
  }
}

/**
 * @member {String} invoiceNumber
 */
InvoiceRequest.prototype.invoiceNumber = undefined;

/**
 * @member {Date} invoiceDate
 */
InvoiceRequest.prototype.invoiceDate = undefined;

/**
 * @member {Array.<module:model/InvoiceItem>} items
 */
InvoiceRequest.prototype.items = undefined;

