/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Dimension} from './Dimension';
import {Handling} from './Handling';
import {NotionalValue} from './NotionalValue';

/**
 * The ModelPackage model module.
 * @module model/ModelPackage
 * @version 3.0
 */
export class ModelPackage {
  /**
   * Constructs a new <code>ModelPackage</code>.
   * @alias module:model/ModelPackage
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>ModelPackage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelPackage} obj Optional instance to populate.
   * @return {module:model/ModelPackage} The populated <code>ModelPackage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModelPackage();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('dimensions'))
        obj.dimensions = Dimension.constructFromObject(data['dimensions']);
      if (data.hasOwnProperty('weight'))
        obj.weight = ApiClient.convertToType(data['weight'], 'Number');
      if (data.hasOwnProperty('notional_value'))
        obj.notionalValue = NotionalValue.constructFromObject(data['notional_value']);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('handling'))
        obj.handling = Handling.constructFromObject(data['handling']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ModelPackage.prototype.id = undefined;

/**
 * @member {String} name
 */
ModelPackage.prototype.name = undefined;

/**
 * @member {module:model/Dimension} dimensions
 */
ModelPackage.prototype.dimensions = undefined;

/**
 * @member {Number} weight
 */
ModelPackage.prototype.weight = undefined;

/**
 * @member {module:model/NotionalValue} notionalValue
 */
ModelPackage.prototype.notionalValue = undefined;

/**
 * @member {String} description
 */
ModelPackage.prototype.description = undefined;

/**
 * @member {module:model/Handling} handling
 */
ModelPackage.prototype.handling = undefined;

