/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NotionalValue model module.
 * @module model/NotionalValue
 * @version 3.0
 */
export class NotionalValue {
  /**
   * Constructs a new <code>NotionalValue</code>.
   * @alias module:model/NotionalValue
   * @class
   * @param amount {Number} 
   * @param unit {module:model/NotionalValue.UnitEnum} 
   */
  constructor(amount, unit) {
    this.amount = amount;
    this.unit = unit;
  }

  /**
   * Constructs a <code>NotionalValue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotionalValue} obj Optional instance to populate.
   * @return {module:model/NotionalValue} The populated <code>NotionalValue</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NotionalValue();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('unit'))
        obj.unit = ApiClient.convertToType(data['unit'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} amount
 */
NotionalValue.prototype.amount = undefined;

/**
 * Allowed values for the <code>unit</code> property.
 * @enum {String}
 * @readonly
 */
NotionalValue.UnitEnum = {
  /**
   * value: "PERCENTAGE"
   * @const
   */
  PERCENTAGE: "PERCENTAGE",

  /**
   * value: "INR"
   * @const
   */
  INR: "INR"
};
/**
 * @member {module:model/NotionalValue.UnitEnum} unit
 */
NotionalValue.prototype.unit = undefined;

