/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {FailedCancellations} from './FailedCancellations';

/**
 * The OrderItemCancelResponse model module.
 * @module model/OrderItemCancelResponse
 * @version 3.0
 */
export class OrderItemCancelResponse {
  /**
   * Constructs a new <code>OrderItemCancelResponse</code>.
   * @alias module:model/OrderItemCancelResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderItemCancelResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderItemCancelResponse} obj Optional instance to populate.
   * @return {module:model/OrderItemCancelResponse} The populated <code>OrderItemCancelResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderItemCancelResponse();
      if (data.hasOwnProperty('cancelled'))
        obj.cancelled = ApiClient.convertToType(data['cancelled'], ['String']);
      if (data.hasOwnProperty('failedCancellations'))
        obj.failedCancellations = ApiClient.convertToType(data['failedCancellations'], [FailedCancellations]);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} cancelled
 */
OrderItemCancelResponse.prototype.cancelled = undefined;

/**
 * @member {Array.<module:model/FailedCancellations>} failedCancellations
 */
OrderItemCancelResponse.prototype.failedCancellations = undefined;

