/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PriceComponents model module.
 * @module model/PriceComponents
 * @version 3.0
 */
export class PriceComponents {
  /**
   * Constructs a new <code>PriceComponents</code>.
   * @alias module:model/PriceComponents
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PriceComponents</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PriceComponents} obj Optional instance to populate.
   * @return {module:model/PriceComponents} The populated <code>PriceComponents</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PriceComponents();
      if (data.hasOwnProperty('sellingPrice'))
        obj.sellingPrice = ApiClient.convertToType(data['sellingPrice'], 'Number');
      if (data.hasOwnProperty('customerPrice'))
        obj.customerPrice = ApiClient.convertToType(data['customerPrice'], 'Number');
      if (data.hasOwnProperty('shippingCharge'))
        obj.shippingCharge = ApiClient.convertToType(data['shippingCharge'], 'Number');
      if (data.hasOwnProperty('totalPrice'))
        obj.totalPrice = ApiClient.convertToType(data['totalPrice'], 'Number');
      if (data.hasOwnProperty('flipkartDiscount'))
        obj.flipkartDiscount = ApiClient.convertToType(data['flipkartDiscount'], 'Number');
      if (data.hasOwnProperty('subsidy'))
        obj.subsidy = ApiClient.convertToType(data['subsidy'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} sellingPrice
 */
PriceComponents.prototype.sellingPrice = undefined;

/**
 * @member {Number} customerPrice
 */
PriceComponents.prototype.customerPrice = undefined;

/**
 * @member {Number} shippingCharge
 */
PriceComponents.prototype.shippingCharge = undefined;

/**
 * @member {Number} totalPrice
 */
PriceComponents.prototype.totalPrice = undefined;

/**
 * @member {Number} flipkartDiscount
 */
PriceComponents.prototype.flipkartDiscount = undefined;

/**
 * @member {Number} subsidy
 */
PriceComponents.prototype.subsidy = undefined;

