/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Price model module.
 * @module model/Price
 * @version 3.0
 */
export class Price {
  /**
   * Constructs a new <code>Price</code>.
   * @alias module:model/Price
   * @class
   * @param mrp {Number} 
   * @param sellingPrice {Number} 
   * @param currency {String} 
   */
  constructor(mrp, sellingPrice, currency) {
    this.mrp = mrp;
    this.sellingPrice = sellingPrice;
    this.currency = currency;
  }

  /**
   * Constructs a <code>Price</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Price} obj Optional instance to populate.
   * @return {module:model/Price} The populated <code>Price</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Price();
      if (data.hasOwnProperty('mrp'))
        obj.mrp = ApiClient.convertToType(data['mrp'], 'Number');
      if (data.hasOwnProperty('selling_price'))
        obj.sellingPrice = ApiClient.convertToType(data['selling_price'], 'Number');
      if (data.hasOwnProperty('mop'))
        obj.mop = ApiClient.convertToType(data['mop'], 'Number');
      if (data.hasOwnProperty('nlc'))
        obj.nlc = ApiClient.convertToType(data['nlc'], 'Number');
      if (data.hasOwnProperty('dealer_price'))
        obj.dealerPrice = ApiClient.convertToType(data['dealer_price'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} mrp
 */
Price.prototype.mrp = undefined;

/**
 * @member {Number} sellingPrice
 */
Price.prototype.sellingPrice = undefined;

/**
 * @member {Number} mop
 */
Price.prototype.mop = undefined;

/**
 * @member {Number} nlc
 */
Price.prototype.nlc = undefined;

/**
 * @member {Number} dealerPrice
 */
Price.prototype.dealerPrice = undefined;

/**
 * @member {String} currency
 */
Price.prototype.currency = undefined;

