/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ReturnItem} from './ReturnItem';

/**
 * The ReturnsSearchResponseV2 model module.
 * @module model/ReturnsSearchResponseV2
 * @version 3.0
 */
export class ReturnsSearchResponseV2 {
  /**
   * Constructs a new <code>ReturnsSearchResponseV2</code>.
   * @alias module:model/ReturnsSearchResponseV2
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReturnsSearchResponseV2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReturnsSearchResponseV2} obj Optional instance to populate.
   * @return {module:model/ReturnsSearchResponseV2} The populated <code>ReturnsSearchResponseV2</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReturnsSearchResponseV2();
      if (data.hasOwnProperty('hasMore'))
        obj.hasMore = ApiClient.convertToType(data['hasMore'], 'Boolean');
      if (data.hasOwnProperty('nextUrl'))
        obj.nextUrl = ApiClient.convertToType(data['nextUrl'], 'String');
      if (data.hasOwnProperty('returnItems'))
        obj.returnItems = ApiClient.convertToType(data['returnItems'], [ReturnItem]);
    }
    return obj;
  }
}

/**
 * @member {Boolean} hasMore
 */
ReturnsSearchResponseV2.prototype.hasMore = undefined;

/**
 * @member {String} nextUrl
 */
ReturnsSearchResponseV2.prototype.nextUrl = undefined;

/**
 * @member {Array.<module:model/ReturnItem>} returnItems
 */
ReturnsSearchResponseV2.prototype.returnItems = undefined;

