/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Service model module.
 * @module model/Service
 * @version 3.0
 */
export class Service {
  /**
   * Constructs a new <code>Service</code>.
   * @alias module:model/Service
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Service</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Service} obj Optional instance to populate.
   * @return {module:model/Service} The populated <code>Service</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Service();
      if (data.hasOwnProperty('serviceFulfilmentId'))
        obj.serviceFulfilmentId = ApiClient.convertToType(data['serviceFulfilmentId'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('serviceByDate'))
        obj.serviceByDate = ApiClient.convertToType(data['serviceByDate'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} serviceFulfilmentId
 */
Service.prototype.serviceFulfilmentId = undefined;

/**
 * @member {String} description
 */
Service.prototype.description = undefined;

/**
 * @member {String} serviceByDate
 */
Service.prototype.serviceByDate = undefined;

/**
 * @member {String} createdAt
 */
Service.prototype.createdAt = undefined;

