/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Address} from './Address';
import {BuyerDetails} from './BuyerDetails';
import {Courier} from './Courier';
import {OrderItem} from './OrderItem';

/**
 * The ShipmentDetails model module.
 * @module model/ShipmentDetails
 * @version 3.0
 */
export class ShipmentDetails {
  /**
   * Constructs a new <code>ShipmentDetails</code>.
   * @alias module:model/ShipmentDetails
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ShipmentDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShipmentDetails} obj Optional instance to populate.
   * @return {module:model/ShipmentDetails} The populated <code>ShipmentDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ShipmentDetails();
      if (data.hasOwnProperty('orderId'))
        obj.orderId = ApiClient.convertToType(data['orderId'], 'String');
      if (data.hasOwnProperty('shipmentId'))
        obj.shipmentId = ApiClient.convertToType(data['shipmentId'], 'String');
      if (data.hasOwnProperty('orderItems'))
        obj.orderItems = ApiClient.convertToType(data['orderItems'], [OrderItem]);
      if (data.hasOwnProperty('weighingRequired'))
        obj.weighingRequired = ApiClient.convertToType(data['weighingRequired'], 'Boolean');
      if (data.hasOwnProperty('deliveryAddress'))
        obj.deliveryAddress = Address.constructFromObject(data['deliveryAddress']);
      if (data.hasOwnProperty('billingAddress'))
        obj.billingAddress = Address.constructFromObject(data['billingAddress']);
      if (data.hasOwnProperty('buyerDetails'))
        obj.buyerDetails = BuyerDetails.constructFromObject(data['buyerDetails']);
      if (data.hasOwnProperty('sellerAddress'))
        obj.sellerAddress = Address.constructFromObject(data['sellerAddress']);
      if (data.hasOwnProperty('returnAddress'))
        obj.returnAddress = Address.constructFromObject(data['returnAddress']);
      if (data.hasOwnProperty('courierDetails'))
        obj.courierDetails = Courier.constructFromObject(data['courierDetails']);
    }
    return obj;
  }
}

/**
 * @member {String} orderId
 */
ShipmentDetails.prototype.orderId = undefined;

/**
 * @member {String} shipmentId
 */
ShipmentDetails.prototype.shipmentId = undefined;

/**
 * @member {Array.<module:model/OrderItem>} orderItems
 */
ShipmentDetails.prototype.orderItems = undefined;

/**
 * @member {Boolean} weighingRequired
 */
ShipmentDetails.prototype.weighingRequired = undefined;

/**
 * @member {module:model/Address} deliveryAddress
 */
ShipmentDetails.prototype.deliveryAddress = undefined;

/**
 * @member {module:model/Address} billingAddress
 */
ShipmentDetails.prototype.billingAddress = undefined;

/**
 * @member {module:model/BuyerDetails} buyerDetails
 */
ShipmentDetails.prototype.buyerDetails = undefined;

/**
 * @member {module:model/Address} sellerAddress
 */
ShipmentDetails.prototype.sellerAddress = undefined;

/**
 * @member {module:model/Address} returnAddress
 */
ShipmentDetails.prototype.returnAddress = undefined;

/**
 * @member {module:model/Courier} courierDetails
 */
ShipmentDetails.prototype.courierDetails = undefined;

