/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ShipmentResponseStatusV2 model module.
 * @module model/ShipmentResponseStatusV2
 * @version 3.0
 */
export class ShipmentResponseStatusV2 {
  /**
   * Constructs a new <code>ShipmentResponseStatusV2</code>.
   * @alias module:model/ShipmentResponseStatusV2
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ShipmentResponseStatusV2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShipmentResponseStatusV2} obj Optional instance to populate.
   * @return {module:model/ShipmentResponseStatusV2} The populated <code>ShipmentResponseStatusV2</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ShipmentResponseStatusV2();
      if (data.hasOwnProperty('shipmentId'))
        obj.shipmentId = ApiClient.convertToType(data['shipmentId'], 'String');
      if (data.hasOwnProperty('processingStatus'))
        obj.processingStatus = ApiClient.convertToType(data['processingStatus'], 'String');
      if (data.hasOwnProperty('errorCode'))
        obj.errorCode = ApiClient.convertToType(data['errorCode'], 'String');
      if (data.hasOwnProperty('errorMessage'))
        obj.errorMessage = ApiClient.convertToType(data['errorMessage'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} shipmentId
 */
ShipmentResponseStatusV2.prototype.shipmentId = undefined;

/**
 * @member {String} processingStatus
 */
ShipmentResponseStatusV2.prototype.processingStatus = undefined;

/**
 * @member {String} errorCode
 */
ShipmentResponseStatusV2.prototype.errorCode = undefined;

/**
 * @member {String} errorMessage
 */
ShipmentResponseStatusV2.prototype.errorMessage = undefined;

