/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ShippingFees model module.
 * @module model/ShippingFees
 * @version 3.0
 */
export class ShippingFees {
  /**
   * Constructs a new <code>ShippingFees</code>.
   * @alias module:model/ShippingFees
   * @class
   * @param local {Number} 
   * @param zonal {Number} 
   * @param national {Number} 
   * @param currency {String} 
   */
  constructor(local, zonal, national, currency) {
    this.local = local;
    this.zonal = zonal;
    this.national = national;
    this.currency = currency;
  }

  /**
   * Constructs a <code>ShippingFees</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShippingFees} obj Optional instance to populate.
   * @return {module:model/ShippingFees} The populated <code>ShippingFees</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ShippingFees();
      if (data.hasOwnProperty('local'))
        obj.local = ApiClient.convertToType(data['local'], 'Number');
      if (data.hasOwnProperty('zonal'))
        obj.zonal = ApiClient.convertToType(data['zonal'], 'Number');
      if (data.hasOwnProperty('national'))
        obj.national = ApiClient.convertToType(data['national'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} local
 */
ShippingFees.prototype.local = undefined;

/**
 * @member {Number} zonal
 */
ShippingFees.prototype.zonal = undefined;

/**
 * @member {Number} national
 */
ShippingFees.prototype.national = undefined;

/**
 * @member {String} currency
 */
ShippingFees.prototype.currency = undefined;

