/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Form} from './Form';
import {OrderItem} from './OrderItem';
import {SubShipment} from './SubShipment';

/**
 * The Shipment model module.
 * @module model/Shipment
 * @version 3.0
 */
export class Shipment {
  /**
   * Constructs a new <code>Shipment</code>.
   * @alias module:model/Shipment
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Shipment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Shipment} obj Optional instance to populate.
   * @return {module:model/Shipment} The populated <code>Shipment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Shipment();
      if (data.hasOwnProperty('shipmentId'))
        obj.shipmentId = ApiClient.convertToType(data['shipmentId'], 'String');
      if (data.hasOwnProperty('dispatchByDate'))
        obj.dispatchByDate = ApiClient.convertToType(data['dispatchByDate'], 'Date');
      if (data.hasOwnProperty('dispatchAfterDate'))
        obj.dispatchAfterDate = ApiClient.convertToType(data['dispatchAfterDate'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('locationId'))
        obj.locationId = ApiClient.convertToType(data['locationId'], 'String');
      if (data.hasOwnProperty('hold'))
        obj.hold = ApiClient.convertToType(data['hold'], 'Boolean');
      if (data.hasOwnProperty('mps'))
        obj.mps = ApiClient.convertToType(data['mps'], 'Boolean');
      if (data.hasOwnProperty('packagingPolicy'))
        obj.packagingPolicy = ApiClient.convertToType(data['packagingPolicy'], 'String');
      if (data.hasOwnProperty('subShipments'))
        obj.subShipments = ApiClient.convertToType(data['subShipments'], [SubShipment]);
      if (data.hasOwnProperty('orderItems'))
        obj.orderItems = ApiClient.convertToType(data['orderItems'], [OrderItem]);
      if (data.hasOwnProperty('forms'))
        obj.forms = ApiClient.convertToType(data['forms'], [Form]);
      if (data.hasOwnProperty('shipmentType'))
        obj.shipmentType = ApiClient.convertToType(data['shipmentType'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} shipmentId
 */
Shipment.prototype.shipmentId = undefined;

/**
 * @member {Date} dispatchByDate
 */
Shipment.prototype.dispatchByDate = undefined;

/**
 * @member {Date} dispatchAfterDate
 */
Shipment.prototype.dispatchAfterDate = undefined;

/**
 * @member {Date} updatedAt
 */
Shipment.prototype.updatedAt = undefined;

/**
 * @member {String} locationId
 */
Shipment.prototype.locationId = undefined;

/**
 * @member {Boolean} hold
 */
Shipment.prototype.hold = undefined;

/**
 * @member {Boolean} mps
 */
Shipment.prototype.mps = undefined;

/**
 * @member {String} packagingPolicy
 */
Shipment.prototype.packagingPolicy = undefined;

/**
 * @member {Array.<module:model/SubShipment>} subShipments
 */
Shipment.prototype.subShipments = undefined;

/**
 * @member {Array.<module:model/OrderItem>} orderItems
 */
Shipment.prototype.orderItems = undefined;

/**
 * @member {Array.<module:model/Form>} forms
 */
Shipment.prototype.forms = undefined;

/**
 * @member {String} shipmentType
 */
Shipment.prototype.shipmentType = undefined;

