/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TaxItem model module.
 * @module model/TaxItem
 * @version 3.0
 */
export class TaxItem {
  /**
   * Constructs a new <code>TaxItem</code>.
   * @alias module:model/TaxItem
   * @class
   * @param taxRate {Number} 
   */
  constructor(taxRate) {
    this.taxRate = taxRate;
  }

  /**
   * Constructs a <code>TaxItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TaxItem} obj Optional instance to populate.
   * @return {module:model/TaxItem} The populated <code>TaxItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TaxItem();
      if (data.hasOwnProperty('orderItemId'))
        obj.orderItemId = ApiClient.convertToType(data['orderItemId'], 'String');
      if (data.hasOwnProperty('purchasePrice'))
        obj.purchasePrice = ApiClient.convertToType(data['purchasePrice'], 'Number');
      if (data.hasOwnProperty('taxRate'))
        obj.taxRate = ApiClient.convertToType(data['taxRate'], 'Number');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} orderItemId
 */
TaxItem.prototype.orderItemId = undefined;

/**
 * @member {Number} purchasePrice
 */
TaxItem.prototype.purchasePrice = undefined;

/**
 * @member {Number} taxRate
 */
TaxItem.prototype.taxRate = undefined;

/**
 * @member {Number} quantity
 */
TaxItem.prototype.quantity = undefined;

