/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FlipkartMarketplaceApi);
  }
}(this, function(expect, FlipkartMarketplaceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PriceComponents', function() {
      beforeEach(function() {
        instance = new FlipkartMarketplaceApi.PriceComponents();
      });

      it('should create an instance of PriceComponents', function() {
        // TODO: update the code to test PriceComponents
        expect(instance).to.be.a(FlipkartMarketplaceApi.PriceComponents);
      });

      it('should have the property sellingPrice (base name: "sellingPrice")', function() {
        // TODO: update the code to test the property sellingPrice
        expect(instance).to.have.property('sellingPrice');
        // expect(instance.sellingPrice).to.be(expectedValueLiteral);
      });

      it('should have the property customerPrice (base name: "customerPrice")', function() {
        // TODO: update the code to test the property customerPrice
        expect(instance).to.have.property('customerPrice');
        // expect(instance.customerPrice).to.be(expectedValueLiteral);
      });

      it('should have the property shippingCharge (base name: "shippingCharge")', function() {
        // TODO: update the code to test the property shippingCharge
        expect(instance).to.have.property('shippingCharge');
        // expect(instance.shippingCharge).to.be(expectedValueLiteral);
      });

      it('should have the property totalPrice (base name: "totalPrice")', function() {
        // TODO: update the code to test the property totalPrice
        expect(instance).to.have.property('totalPrice');
        // expect(instance.totalPrice).to.be(expectedValueLiteral);
      });

      it('should have the property flipkartDiscount (base name: "flipkartDiscount")', function() {
        // TODO: update the code to test the property flipkartDiscount
        expect(instance).to.have.property('flipkartDiscount');
        // expect(instance.flipkartDiscount).to.be(expectedValueLiteral);
      });

      it('should have the property subsidy (base name: "subsidy")', function() {
        // TODO: update the code to test the property subsidy
        expect(instance).to.have.property('subsidy');
        // expect(instance.subsidy).to.be(expectedValueLiteral);
      });

    });
  });

}));
