/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FlipkartMarketplaceApi);
  }
}(this, function(expect, FlipkartMarketplaceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SelfShipReturnAttemptPickupRequest', function() {
      beforeEach(function() {
        instance = new FlipkartMarketplaceApi.SelfShipReturnAttemptPickupRequest();
      });

      it('should create an instance of SelfShipReturnAttemptPickupRequest', function() {
        // TODO: update the code to test SelfShipReturnAttemptPickupRequest
        expect(instance).to.be.a(FlipkartMarketplaceApi.SelfShipReturnAttemptPickupRequest);
      });

      it('should have the property returnId (base name: "returnId")', function() {
        // TODO: update the code to test the property returnId
        expect(instance).to.have.property('returnId');
        // expect(instance.returnId).to.be(expectedValueLiteral);
      });

      it('should have the property pickupDate (base name: "pickupDate")', function() {
        // TODO: update the code to test the property pickupDate
        expect(instance).to.have.property('pickupDate');
        // expect(instance.pickupDate).to.be(expectedValueLiteral);
      });

      it('should have the property newPickupDate (base name: "newPickupDate")', function() {
        // TODO: update the code to test the property newPickupDate
        expect(instance).to.have.property('newPickupDate');
        // expect(instance.newPickupDate).to.be(expectedValueLiteral);
      });

      it('should have the property reason (base name: "reason")', function() {
        // TODO: update the code to test the property reason
        expect(instance).to.have.property('reason');
        // expect(instance.reason).to.be(expectedValueLiteral);
      });

    });
  });

}));
