/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FlipkartMarketplaceApi);
  }
}(this, function(expect, FlipkartMarketplaceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UpdateHyperlocalListingRequest', function() {
      beforeEach(function() {
        instance = new FlipkartMarketplaceApi.UpdateHyperlocalListingRequest();
      });

      it('should create an instance of UpdateHyperlocalListingRequest', function() {
        // TODO: update the code to test UpdateHyperlocalListingRequest
        expect(instance).to.be.a(FlipkartMarketplaceApi.UpdateHyperlocalListingRequest);
      });

      it('should have the property productId (base name: "product_id")', function() {
        // TODO: update the code to test the property productId
        expect(instance).to.have.property('productId');
        // expect(instance.productId).to.be(expectedValueLiteral);
      });

      it('should have the property price (base name: "price")', function() {
        // TODO: update the code to test the property price
        expect(instance).to.have.property('price');
        // expect(instance.price).to.be(expectedValueLiteral);
      });

      it('should have the property tax (base name: "tax")', function() {
        // TODO: update the code to test the property tax
        expect(instance).to.have.property('tax');
        // expect(instance.tax).to.be(expectedValueLiteral);
      });

      it('should have the property listingStatus (base name: "listing_status")', function() {
        // TODO: update the code to test the property listingStatus
        expect(instance).to.have.property('listingStatus');
        // expect(instance.listingStatus).to.be(expectedValueLiteral);
      });

      it('should have the property _package (base name: "package")', function() {
        // TODO: update the code to test the property _package
        expect(instance).to.have.property('_package');
        // expect(instance._package).to.be(expectedValueLiteral);
      });

      it('should have the property location (base name: "location")', function() {
        // TODO: update the code to test the property location
        expect(instance).to.have.property('location');
        // expect(instance.location).to.be(expectedValueLiteral);
      });

      it('should have the property addressLabel (base name: "address_label")', function() {
        // TODO: update the code to test the property addressLabel
        expect(instance).to.have.property('addressLabel');
        // expect(instance.addressLabel).to.be(expectedValueLiteral);
      });

      it('should have the property datingLabel (base name: "dating_label")', function() {
        // TODO: update the code to test the property datingLabel
        expect(instance).to.have.property('datingLabel');
        // expect(instance.datingLabel).to.be(expectedValueLiteral);
      });

      it('should have the property archivedStatus (base name: "archived_status")', function() {
        // TODO: update the code to test the property archivedStatus
        expect(instance).to.have.property('archivedStatus');
        // expect(instance.archivedStatus).to.be(expectedValueLiteral);
      });

    });
  });

}));
