/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FlipkartMarketplaceApi);
  }
}(this, function(expect, FlipkartMarketplaceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('VendorGroupCodeDetailsResponseV3', function() {
      beforeEach(function() {
        instance = new FlipkartMarketplaceApi.VendorGroupCodeDetailsResponseV3();
      });

      it('should create an instance of VendorGroupCodeDetailsResponseV3', function() {
        // TODO: update the code to test VendorGroupCodeDetailsResponseV3
        expect(instance).to.be.a(FlipkartMarketplaceApi.VendorGroupCodeDetailsResponseV3);
      });

      it('should have the property vendorGroupCode (base name: "vendorGroupCode")', function() {
        // TODO: update the code to test the property vendorGroupCode
        expect(instance).to.have.property('vendorGroupCode');
        // expect(instance.vendorGroupCode).to.be(expectedValueLiteral);
      });

      it('should have the property count (base name: "count")', function() {
        // TODO: update the code to test the property count
        expect(instance).to.have.property('count');
        // expect(instance.count).to.be(expectedValueLiteral);
      });

      it('should have the property pickUpDate (base name: "pickUpDate")', function() {
        // TODO: update the code to test the property pickUpDate
        expect(instance).to.have.property('pickUpDate');
        // expect(instance.pickUpDate).to.be(expectedValueLiteral);
      });

      it('should have the property otc (base name: "otc")', function() {
        // TODO: update the code to test the property otc
        expect(instance).to.have.property('otc');
        // expect(instance.otc).to.be(expectedValueLiteral);
      });

      it('should have the property isMps (base name: "isMps")', function() {
        // TODO: update the code to test the property isMps
        expect(instance).to.have.property('isMps');
        // expect(instance.isMps).to.be(expectedValueLiteral);
      });

    });
  });

}));
