/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Address} from './model/Address';
import {AddressLabel} from './model/AddressLabel';
import {AttributeError} from './model/AttributeError';
import {BulkActionProgressResponse} from './model/BulkActionProgressResponse';
import {BulkConfirmItem} from './model/BulkConfirmItem';
import {BulkConfirmResponseV2} from './model/BulkConfirmResponseV2';
import {BulkConfirmedItem} from './model/BulkConfirmedItem';
import {BulkOrderItem} from './model/BulkOrderItem';
import {BulkRtdActionRequest} from './model/BulkRtdActionRequest';
import {BulkRtdRequestItemStatus} from './model/BulkRtdRequestItemStatus';
import {BulkRtdResponse} from './model/BulkRtdResponse';
import {BuyerDetails} from './model/BuyerDetails';
import {CancelOrderItemRequest} from './model/CancelOrderItemRequest';
import {CancelRequestV2} from './model/CancelRequestV2';
import {CancelShipment} from './model/CancelShipment';
import {CancelShipmentRequest} from './model/CancelShipmentRequest';
import {ChangeDispatchSlots} from './model/ChangeDispatchSlots';
import {ConfirmItemRow} from './model/ConfirmItemRow';
import {Courier} from './model/Courier';
import {CourierDetails} from './model/CourierDetails';
import {CreateCourierReturnRequest} from './model/CreateCourierReturnRequest';
import {CreateCourierReturnResponse} from './model/CreateCourierReturnResponse';
import {CreateHyperlocalListingRequest} from './model/CreateHyperlocalListingRequest';
import {CreateListingRequest} from './model/CreateListingRequest';
import {CreateOrderItem} from './model/CreateOrderItem';
import {CreateOrderItemResponse} from './model/CreateOrderItemResponse';
import {CreateService} from './model/CreateService';
import {CreateTestOrdersRequest} from './model/CreateTestOrdersRequest';
import {CreateTestOrdersResponse} from './model/CreateTestOrdersResponse';
import {Currency} from './model/Currency';
import {DateFilter} from './model/DateFilter';
import {DatingLabel} from './model/DatingLabel';
import {DeliverRequest} from './model/DeliverRequest';
import {Dimension} from './model/Dimension';
import {Dimensions} from './model/Dimensions';
import {DispatchAddress} from './model/DispatchAddress';
import {DispatchLocation} from './model/DispatchLocation';
import {DispatchRequest} from './model/DispatchRequest';
import {DispatchRequestV3} from './model/DispatchRequestV3';
import {DispatchShipmentRequest} from './model/DispatchShipmentRequest';
import {Error} from './model/Error';
import {FailedCancellations} from './model/FailedCancellations';
import {FailureAttributes} from './model/FailureAttributes';
import {FetchOrderItemsResponse} from './model/FetchOrderItemsResponse';
import {Filter} from './model/Filter';
import {Form} from './model/Form';
import {Fulfillment} from './model/Fulfillment';
import {GenerateLabelRequestItemV2} from './model/GenerateLabelRequestItemV2';
import {GenerateLabelRequestV2} from './model/GenerateLabelRequestV2';
import {GetManifestRequest} from './model/GetManifestRequest';
import {GetMarketplaceListingDetailsResponse} from './model/GetMarketplaceListingDetailsResponse';
import {Handling} from './model/Handling';
import {InputStream} from './model/InputStream';
import {Invoice} from './model/Invoice';
import {InvoiceDetails} from './model/InvoiceDetails';
import {InvoiceDetailsResponseV3} from './model/InvoiceDetailsResponseV3';
import {InvoiceItem} from './model/InvoiceItem';
import {InvoiceRequest} from './model/InvoiceRequest';
import {InvoicesSearchResponseV2} from './model/InvoicesSearchResponseV2';
import {ListingChangeResponse} from './model/ListingChangeResponse';
import {Location} from './model/Location';
import {MakeOrderUnHold} from './model/MakeOrderUnHold';
import {MarkOrderItemDelivered} from './model/MarkOrderItemDelivered';
import {MarkOrderItemPickupComplete} from './model/MarkOrderItemPickupComplete';
import {MarkOrderItemShipped} from './model/MarkOrderItemShipped';
import {MarketplaceListingDetail} from './model/MarketplaceListingDetail';
import {ModelPackage} from './model/ModelPackage';
import {NotionalValue} from './model/NotionalValue';
import {OrderItem} from './model/OrderItem';
import {OrderItemCancelResponse} from './model/OrderItemCancelResponse';
import {OrderItems} from './model/OrderItems';
import {Otc} from './model/Otc';
import {PackRequest} from './model/PackRequest';
import {Pagination} from './model/Pagination';
import {Params} from './model/Params';
import {PickUpDate} from './model/PickUpDate';
import {Price} from './model/Price';
import {PriceComponent} from './model/PriceComponent';
import {PriceComponents} from './model/PriceComponents';
import {ProcessReturnEvents} from './model/ProcessReturnEvents';
import {PutOrderOnHold} from './model/PutOrderOnHold';
import {RequestStatus} from './model/RequestStatus';
import {ReturnActionResponse} from './model/ReturnActionResponse';
import {ReturnApproveRequest} from './model/ReturnApproveRequest';
import {ReturnItem} from './model/ReturnItem';
import {ReturnRejectRequest} from './model/ReturnRejectRequest';
import {ReturnsActionResponseV2} from './model/ReturnsActionResponseV2';
import {ReturnsApproveRequest} from './model/ReturnsApproveRequest';
import {ReturnsRejectRequest} from './model/ReturnsRejectRequest';
import {ReturnsSearchResponseV2} from './model/ReturnsSearchResponseV2';
import {SearchOrderItemRequest} from './model/SearchOrderItemRequest';
import {SearchOrderItemResponseV2} from './model/SearchOrderItemResponseV2';
import {SearchShipmentRequest} from './model/SearchShipmentRequest';
import {SearchShipmentResponse} from './model/SearchShipmentResponse';
import {SelfShipReturnAttemptPickupRequest} from './model/SelfShipReturnAttemptPickupRequest';
import {SelfShipReturnCancellationRequest} from './model/SelfShipReturnCancellationRequest';
import {SelfShipReturnCompleteRequest} from './model/SelfShipReturnCompleteRequest';
import {SelfShipReturnPickupAttemptRequests} from './model/SelfShipReturnPickupAttemptRequests';
import {SelfShipReturnPickupRequest} from './model/SelfShipReturnPickupRequest';
import {SelfShipReturnPickupRequests} from './model/SelfShipReturnPickupRequests';
import {SelfshipDispatchRequestV3} from './model/SelfshipDispatchRequestV3';
import {SellerAddress} from './model/SellerAddress';
import {SerialNumber} from './model/SerialNumber';
import {Service} from './model/Service';
import {ServiceAttemptRequest} from './model/ServiceAttemptRequest';
import {ServiceCompleteRequest} from './model/ServiceCompleteRequest';
import {ServiceResponseStatusV2} from './model/ServiceResponseStatusV2';
import {Shipment} from './model/Shipment';
import {ShipmentDetails} from './model/ShipmentDetails';
import {ShipmentDetailsResponseV3} from './model/ShipmentDetailsResponseV3';
import {ShipmentPackRequest} from './model/ShipmentPackRequest';
import {ShipmentResponse} from './model/ShipmentResponse';
import {ShipmentResponseStatusV2} from './model/ShipmentResponseStatusV2';
import {ShipmentSearchResponse} from './model/ShipmentSearchResponse';
import {ShipmentStatusResponse} from './model/ShipmentStatusResponse';
import {ShipmentsDeliverAttemptRequestV2} from './model/ShipmentsDeliverAttemptRequestV2';
import {ShipmentsDeliverRequestV2} from './model/ShipmentsDeliverRequestV2';
import {ShipmentsDeliverResponseV2} from './model/ShipmentsDeliverResponseV2';
import {ShipmentsDispatchRequestV2} from './model/ShipmentsDispatchRequestV2';
import {ShipmentsDispatchResponseV2} from './model/ShipmentsDispatchResponseV2';
import {ShippingFees} from './model/ShippingFees';
import {Sort} from './model/Sort';
import {SubItemRequest} from './model/SubItemRequest';
import {SubItemResponse} from './model/SubItemResponse';
import {SubShipment} from './model/SubShipment';
import {SubShipments} from './model/SubShipments';
import {Tax} from './model/Tax';
import {TaxDetails} from './model/TaxDetails';
import {TaxItem} from './model/TaxItem';
import {UpdateHyperlocalListingRequest} from './model/UpdateHyperlocalListingRequest';
import {UpdateInventoryRequest} from './model/UpdateInventoryRequest';
import {UpdateListingRequest} from './model/UpdateListingRequest';
import {UpdatePriceRequest} from './model/UpdatePriceRequest';
import {UpdateShipmentRequest} from './model/UpdateShipmentRequest';
import {VendorGroupCodeDetailsResponseV3} from './model/VendorGroupCodeDetailsResponseV3';
import {ListingsCommonV3Api} from './api/ListingsCommonV3Api';
import {ListingsFlipkartV3Api} from './api/ListingsFlipkartV3Api';
import {ListingsHyperlocalV3Api} from './api/ListingsHyperlocalV3Api';
import {OrdersV2Api} from './api/OrdersV2Api';
import {ReturnsV2Api} from './api/ReturnsV2Api';
import {SelfServeApi} from './api/SelfServeApi';
import {ShipmentV3Api} from './api/ShipmentV3Api';

/**
* This_API_is_offered_by_Flipkart_Marketplace_to_sellers_and_partners_for_orders_and_listing_management__br_br_You_will_need_an_access_token_to_explore_our_APIs_in_the_sandbox_environment__For_details_on_getting_an_access_token_refer_to_the_a_hrefhttpsseller_flipkart_comapi_docsFMSAPI_htmlsandbox_environment_documentationa__br_Once_you_get_the_access_token_use_it_to_authorize_the_requests_using_the__codeAuthorizecode_button_below__e_g__if_your_access_token_is_codeACCTOK1code_the_input_for_authorization_should_be_codeBearer_ACCTOK1code.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FlipkartMarketplaceApi = require('index'); // See note below*.
* var xxxSvc = new FlipkartMarketplaceApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FlipkartMarketplaceApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FlipkartMarketplaceApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FlipkartMarketplaceApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 3.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address,

    /**
     * The AddressLabel model constructor.
     * @property {module:model/AddressLabel}
     */
    AddressLabel,

    /**
     * The AttributeError model constructor.
     * @property {module:model/AttributeError}
     */
    AttributeError,

    /**
     * The BulkActionProgressResponse model constructor.
     * @property {module:model/BulkActionProgressResponse}
     */
    BulkActionProgressResponse,

    /**
     * The BulkConfirmItem model constructor.
     * @property {module:model/BulkConfirmItem}
     */
    BulkConfirmItem,

    /**
     * The BulkConfirmResponseV2 model constructor.
     * @property {module:model/BulkConfirmResponseV2}
     */
    BulkConfirmResponseV2,

    /**
     * The BulkConfirmedItem model constructor.
     * @property {module:model/BulkConfirmedItem}
     */
    BulkConfirmedItem,

    /**
     * The BulkOrderItem model constructor.
     * @property {module:model/BulkOrderItem}
     */
    BulkOrderItem,

    /**
     * The BulkRtdActionRequest model constructor.
     * @property {module:model/BulkRtdActionRequest}
     */
    BulkRtdActionRequest,

    /**
     * The BulkRtdRequestItemStatus model constructor.
     * @property {module:model/BulkRtdRequestItemStatus}
     */
    BulkRtdRequestItemStatus,

    /**
     * The BulkRtdResponse model constructor.
     * @property {module:model/BulkRtdResponse}
     */
    BulkRtdResponse,

    /**
     * The BuyerDetails model constructor.
     * @property {module:model/BuyerDetails}
     */
    BuyerDetails,

    /**
     * The CancelOrderItemRequest model constructor.
     * @property {module:model/CancelOrderItemRequest}
     */
    CancelOrderItemRequest,

    /**
     * The CancelRequestV2 model constructor.
     * @property {module:model/CancelRequestV2}
     */
    CancelRequestV2,

    /**
     * The CancelShipment model constructor.
     * @property {module:model/CancelShipment}
     */
    CancelShipment,

    /**
     * The CancelShipmentRequest model constructor.
     * @property {module:model/CancelShipmentRequest}
     */
    CancelShipmentRequest,

    /**
     * The ChangeDispatchSlots model constructor.
     * @property {module:model/ChangeDispatchSlots}
     */
    ChangeDispatchSlots,

    /**
     * The ConfirmItemRow model constructor.
     * @property {module:model/ConfirmItemRow}
     */
    ConfirmItemRow,

    /**
     * The Courier model constructor.
     * @property {module:model/Courier}
     */
    Courier,

    /**
     * The CourierDetails model constructor.
     * @property {module:model/CourierDetails}
     */
    CourierDetails,

    /**
     * The CreateCourierReturnRequest model constructor.
     * @property {module:model/CreateCourierReturnRequest}
     */
    CreateCourierReturnRequest,

    /**
     * The CreateCourierReturnResponse model constructor.
     * @property {module:model/CreateCourierReturnResponse}
     */
    CreateCourierReturnResponse,

    /**
     * The CreateHyperlocalListingRequest model constructor.
     * @property {module:model/CreateHyperlocalListingRequest}
     */
    CreateHyperlocalListingRequest,

    /**
     * The CreateListingRequest model constructor.
     * @property {module:model/CreateListingRequest}
     */
    CreateListingRequest,

    /**
     * The CreateOrderItem model constructor.
     * @property {module:model/CreateOrderItem}
     */
    CreateOrderItem,

    /**
     * The CreateOrderItemResponse model constructor.
     * @property {module:model/CreateOrderItemResponse}
     */
    CreateOrderItemResponse,

    /**
     * The CreateService model constructor.
     * @property {module:model/CreateService}
     */
    CreateService,

    /**
     * The CreateTestOrdersRequest model constructor.
     * @property {module:model/CreateTestOrdersRequest}
     */
    CreateTestOrdersRequest,

    /**
     * The CreateTestOrdersResponse model constructor.
     * @property {module:model/CreateTestOrdersResponse}
     */
    CreateTestOrdersResponse,

    /**
     * The Currency model constructor.
     * @property {module:model/Currency}
     */
    Currency,

    /**
     * The DateFilter model constructor.
     * @property {module:model/DateFilter}
     */
    DateFilter,

    /**
     * The DatingLabel model constructor.
     * @property {module:model/DatingLabel}
     */
    DatingLabel,

    /**
     * The DeliverRequest model constructor.
     * @property {module:model/DeliverRequest}
     */
    DeliverRequest,

    /**
     * The Dimension model constructor.
     * @property {module:model/Dimension}
     */
    Dimension,

    /**
     * The Dimensions model constructor.
     * @property {module:model/Dimensions}
     */
    Dimensions,

    /**
     * The DispatchAddress model constructor.
     * @property {module:model/DispatchAddress}
     */
    DispatchAddress,

    /**
     * The DispatchLocation model constructor.
     * @property {module:model/DispatchLocation}
     */
    DispatchLocation,

    /**
     * The DispatchRequest model constructor.
     * @property {module:model/DispatchRequest}
     */
    DispatchRequest,

    /**
     * The DispatchRequestV3 model constructor.
     * @property {module:model/DispatchRequestV3}
     */
    DispatchRequestV3,

    /**
     * The DispatchShipmentRequest model constructor.
     * @property {module:model/DispatchShipmentRequest}
     */
    DispatchShipmentRequest,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The FailedCancellations model constructor.
     * @property {module:model/FailedCancellations}
     */
    FailedCancellations,

    /**
     * The FailureAttributes model constructor.
     * @property {module:model/FailureAttributes}
     */
    FailureAttributes,

    /**
     * The FetchOrderItemsResponse model constructor.
     * @property {module:model/FetchOrderItemsResponse}
     */
    FetchOrderItemsResponse,

    /**
     * The Filter model constructor.
     * @property {module:model/Filter}
     */
    Filter,

    /**
     * The Form model constructor.
     * @property {module:model/Form}
     */
    Form,

    /**
     * The Fulfillment model constructor.
     * @property {module:model/Fulfillment}
     */
    Fulfillment,

    /**
     * The GenerateLabelRequestItemV2 model constructor.
     * @property {module:model/GenerateLabelRequestItemV2}
     */
    GenerateLabelRequestItemV2,

    /**
     * The GenerateLabelRequestV2 model constructor.
     * @property {module:model/GenerateLabelRequestV2}
     */
    GenerateLabelRequestV2,

    /**
     * The GetManifestRequest model constructor.
     * @property {module:model/GetManifestRequest}
     */
    GetManifestRequest,

    /**
     * The GetMarketplaceListingDetailsResponse model constructor.
     * @property {module:model/GetMarketplaceListingDetailsResponse}
     */
    GetMarketplaceListingDetailsResponse,

    /**
     * The Handling model constructor.
     * @property {module:model/Handling}
     */
    Handling,

    /**
     * The InputStream model constructor.
     * @property {module:model/InputStream}
     */
    InputStream,

    /**
     * The Invoice model constructor.
     * @property {module:model/Invoice}
     */
    Invoice,

    /**
     * The InvoiceDetails model constructor.
     * @property {module:model/InvoiceDetails}
     */
    InvoiceDetails,

    /**
     * The InvoiceDetailsResponseV3 model constructor.
     * @property {module:model/InvoiceDetailsResponseV3}
     */
    InvoiceDetailsResponseV3,

    /**
     * The InvoiceItem model constructor.
     * @property {module:model/InvoiceItem}
     */
    InvoiceItem,

    /**
     * The InvoiceRequest model constructor.
     * @property {module:model/InvoiceRequest}
     */
    InvoiceRequest,

    /**
     * The InvoicesSearchResponseV2 model constructor.
     * @property {module:model/InvoicesSearchResponseV2}
     */
    InvoicesSearchResponseV2,

    /**
     * The ListingChangeResponse model constructor.
     * @property {module:model/ListingChangeResponse}
     */
    ListingChangeResponse,

    /**
     * The Location model constructor.
     * @property {module:model/Location}
     */
    Location,

    /**
     * The MakeOrderUnHold model constructor.
     * @property {module:model/MakeOrderUnHold}
     */
    MakeOrderUnHold,

    /**
     * The MarkOrderItemDelivered model constructor.
     * @property {module:model/MarkOrderItemDelivered}
     */
    MarkOrderItemDelivered,

    /**
     * The MarkOrderItemPickupComplete model constructor.
     * @property {module:model/MarkOrderItemPickupComplete}
     */
    MarkOrderItemPickupComplete,

    /**
     * The MarkOrderItemShipped model constructor.
     * @property {module:model/MarkOrderItemShipped}
     */
    MarkOrderItemShipped,

    /**
     * The MarketplaceListingDetail model constructor.
     * @property {module:model/MarketplaceListingDetail}
     */
    MarketplaceListingDetail,

    /**
     * The ModelPackage model constructor.
     * @property {module:model/ModelPackage}
     */
    ModelPackage,

    /**
     * The NotionalValue model constructor.
     * @property {module:model/NotionalValue}
     */
    NotionalValue,

    /**
     * The OrderItem model constructor.
     * @property {module:model/OrderItem}
     */
    OrderItem,

    /**
     * The OrderItemCancelResponse model constructor.
     * @property {module:model/OrderItemCancelResponse}
     */
    OrderItemCancelResponse,

    /**
     * The OrderItems model constructor.
     * @property {module:model/OrderItems}
     */
    OrderItems,

    /**
     * The Otc model constructor.
     * @property {module:model/Otc}
     */
    Otc,

    /**
     * The PackRequest model constructor.
     * @property {module:model/PackRequest}
     */
    PackRequest,

    /**
     * The Pagination model constructor.
     * @property {module:model/Pagination}
     */
    Pagination,

    /**
     * The Params model constructor.
     * @property {module:model/Params}
     */
    Params,

    /**
     * The PickUpDate model constructor.
     * @property {module:model/PickUpDate}
     */
    PickUpDate,

    /**
     * The Price model constructor.
     * @property {module:model/Price}
     */
    Price,

    /**
     * The PriceComponent model constructor.
     * @property {module:model/PriceComponent}
     */
    PriceComponent,

    /**
     * The PriceComponents model constructor.
     * @property {module:model/PriceComponents}
     */
    PriceComponents,

    /**
     * The ProcessReturnEvents model constructor.
     * @property {module:model/ProcessReturnEvents}
     */
    ProcessReturnEvents,

    /**
     * The PutOrderOnHold model constructor.
     * @property {module:model/PutOrderOnHold}
     */
    PutOrderOnHold,

    /**
     * The RequestStatus model constructor.
     * @property {module:model/RequestStatus}
     */
    RequestStatus,

    /**
     * The ReturnActionResponse model constructor.
     * @property {module:model/ReturnActionResponse}
     */
    ReturnActionResponse,

    /**
     * The ReturnApproveRequest model constructor.
     * @property {module:model/ReturnApproveRequest}
     */
    ReturnApproveRequest,

    /**
     * The ReturnItem model constructor.
     * @property {module:model/ReturnItem}
     */
    ReturnItem,

    /**
     * The ReturnRejectRequest model constructor.
     * @property {module:model/ReturnRejectRequest}
     */
    ReturnRejectRequest,

    /**
     * The ReturnsActionResponseV2 model constructor.
     * @property {module:model/ReturnsActionResponseV2}
     */
    ReturnsActionResponseV2,

    /**
     * The ReturnsApproveRequest model constructor.
     * @property {module:model/ReturnsApproveRequest}
     */
    ReturnsApproveRequest,

    /**
     * The ReturnsRejectRequest model constructor.
     * @property {module:model/ReturnsRejectRequest}
     */
    ReturnsRejectRequest,

    /**
     * The ReturnsSearchResponseV2 model constructor.
     * @property {module:model/ReturnsSearchResponseV2}
     */
    ReturnsSearchResponseV2,

    /**
     * The SearchOrderItemRequest model constructor.
     * @property {module:model/SearchOrderItemRequest}
     */
    SearchOrderItemRequest,

    /**
     * The SearchOrderItemResponseV2 model constructor.
     * @property {module:model/SearchOrderItemResponseV2}
     */
    SearchOrderItemResponseV2,

    /**
     * The SearchShipmentRequest model constructor.
     * @property {module:model/SearchShipmentRequest}
     */
    SearchShipmentRequest,

    /**
     * The SearchShipmentResponse model constructor.
     * @property {module:model/SearchShipmentResponse}
     */
    SearchShipmentResponse,

    /**
     * The SelfShipReturnAttemptPickupRequest model constructor.
     * @property {module:model/SelfShipReturnAttemptPickupRequest}
     */
    SelfShipReturnAttemptPickupRequest,

    /**
     * The SelfShipReturnCancellationRequest model constructor.
     * @property {module:model/SelfShipReturnCancellationRequest}
     */
    SelfShipReturnCancellationRequest,

    /**
     * The SelfShipReturnCompleteRequest model constructor.
     * @property {module:model/SelfShipReturnCompleteRequest}
     */
    SelfShipReturnCompleteRequest,

    /**
     * The SelfShipReturnPickupAttemptRequests model constructor.
     * @property {module:model/SelfShipReturnPickupAttemptRequests}
     */
    SelfShipReturnPickupAttemptRequests,

    /**
     * The SelfShipReturnPickupRequest model constructor.
     * @property {module:model/SelfShipReturnPickupRequest}
     */
    SelfShipReturnPickupRequest,

    /**
     * The SelfShipReturnPickupRequests model constructor.
     * @property {module:model/SelfShipReturnPickupRequests}
     */
    SelfShipReturnPickupRequests,

    /**
     * The SelfshipDispatchRequestV3 model constructor.
     * @property {module:model/SelfshipDispatchRequestV3}
     */
    SelfshipDispatchRequestV3,

    /**
     * The SellerAddress model constructor.
     * @property {module:model/SellerAddress}
     */
    SellerAddress,

    /**
     * The SerialNumber model constructor.
     * @property {module:model/SerialNumber}
     */
    SerialNumber,

    /**
     * The Service model constructor.
     * @property {module:model/Service}
     */
    Service,

    /**
     * The ServiceAttemptRequest model constructor.
     * @property {module:model/ServiceAttemptRequest}
     */
    ServiceAttemptRequest,

    /**
     * The ServiceCompleteRequest model constructor.
     * @property {module:model/ServiceCompleteRequest}
     */
    ServiceCompleteRequest,

    /**
     * The ServiceResponseStatusV2 model constructor.
     * @property {module:model/ServiceResponseStatusV2}
     */
    ServiceResponseStatusV2,

    /**
     * The Shipment model constructor.
     * @property {module:model/Shipment}
     */
    Shipment,

    /**
     * The ShipmentDetails model constructor.
     * @property {module:model/ShipmentDetails}
     */
    ShipmentDetails,

    /**
     * The ShipmentDetailsResponseV3 model constructor.
     * @property {module:model/ShipmentDetailsResponseV3}
     */
    ShipmentDetailsResponseV3,

    /**
     * The ShipmentPackRequest model constructor.
     * @property {module:model/ShipmentPackRequest}
     */
    ShipmentPackRequest,

    /**
     * The ShipmentResponse model constructor.
     * @property {module:model/ShipmentResponse}
     */
    ShipmentResponse,

    /**
     * The ShipmentResponseStatusV2 model constructor.
     * @property {module:model/ShipmentResponseStatusV2}
     */
    ShipmentResponseStatusV2,

    /**
     * The ShipmentSearchResponse model constructor.
     * @property {module:model/ShipmentSearchResponse}
     */
    ShipmentSearchResponse,

    /**
     * The ShipmentStatusResponse model constructor.
     * @property {module:model/ShipmentStatusResponse}
     */
    ShipmentStatusResponse,

    /**
     * The ShipmentsDeliverAttemptRequestV2 model constructor.
     * @property {module:model/ShipmentsDeliverAttemptRequestV2}
     */
    ShipmentsDeliverAttemptRequestV2,

    /**
     * The ShipmentsDeliverRequestV2 model constructor.
     * @property {module:model/ShipmentsDeliverRequestV2}
     */
    ShipmentsDeliverRequestV2,

    /**
     * The ShipmentsDeliverResponseV2 model constructor.
     * @property {module:model/ShipmentsDeliverResponseV2}
     */
    ShipmentsDeliverResponseV2,

    /**
     * The ShipmentsDispatchRequestV2 model constructor.
     * @property {module:model/ShipmentsDispatchRequestV2}
     */
    ShipmentsDispatchRequestV2,

    /**
     * The ShipmentsDispatchResponseV2 model constructor.
     * @property {module:model/ShipmentsDispatchResponseV2}
     */
    ShipmentsDispatchResponseV2,

    /**
     * The ShippingFees model constructor.
     * @property {module:model/ShippingFees}
     */
    ShippingFees,

    /**
     * The Sort model constructor.
     * @property {module:model/Sort}
     */
    Sort,

    /**
     * The SubItemRequest model constructor.
     * @property {module:model/SubItemRequest}
     */
    SubItemRequest,

    /**
     * The SubItemResponse model constructor.
     * @property {module:model/SubItemResponse}
     */
    SubItemResponse,

    /**
     * The SubShipment model constructor.
     * @property {module:model/SubShipment}
     */
    SubShipment,

    /**
     * The SubShipments model constructor.
     * @property {module:model/SubShipments}
     */
    SubShipments,

    /**
     * The Tax model constructor.
     * @property {module:model/Tax}
     */
    Tax,

    /**
     * The TaxDetails model constructor.
     * @property {module:model/TaxDetails}
     */
    TaxDetails,

    /**
     * The TaxItem model constructor.
     * @property {module:model/TaxItem}
     */
    TaxItem,

    /**
     * The UpdateHyperlocalListingRequest model constructor.
     * @property {module:model/UpdateHyperlocalListingRequest}
     */
    UpdateHyperlocalListingRequest,

    /**
     * The UpdateInventoryRequest model constructor.
     * @property {module:model/UpdateInventoryRequest}
     */
    UpdateInventoryRequest,

    /**
     * The UpdateListingRequest model constructor.
     * @property {module:model/UpdateListingRequest}
     */
    UpdateListingRequest,

    /**
     * The UpdatePriceRequest model constructor.
     * @property {module:model/UpdatePriceRequest}
     */
    UpdatePriceRequest,

    /**
     * The UpdateShipmentRequest model constructor.
     * @property {module:model/UpdateShipmentRequest}
     */
    UpdateShipmentRequest,

    /**
     * The VendorGroupCodeDetailsResponseV3 model constructor.
     * @property {module:model/VendorGroupCodeDetailsResponseV3}
     */
    VendorGroupCodeDetailsResponseV3,

    /**
    * The ListingsCommonV3Api service constructor.
    * @property {module:api/ListingsCommonV3Api}
    */
    ListingsCommonV3Api,

    /**
    * The ListingsFlipkartV3Api service constructor.
    * @property {module:api/ListingsFlipkartV3Api}
    */
    ListingsFlipkartV3Api,

    /**
    * The ListingsHyperlocalV3Api service constructor.
    * @property {module:api/ListingsHyperlocalV3Api}
    */
    ListingsHyperlocalV3Api,

    /**
    * The OrdersV2Api service constructor.
    * @property {module:api/OrdersV2Api}
    */
    OrdersV2Api,

    /**
    * The ReturnsV2Api service constructor.
    * @property {module:api/ReturnsV2Api}
    */
    ReturnsV2Api,

    /**
    * The SelfServeApi service constructor.
    * @property {module:api/SelfServeApi}
    */
    SelfServeApi,

    /**
    * The ShipmentV3Api service constructor.
    * @property {module:api/ShipmentV3Api}
    */
    ShipmentV3Api
};
