/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FlipkartMarketplaceApi);
  }
}(this, function(expect, FlipkartMarketplaceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FlipkartMarketplaceApi.ReturnsV2Api();
  });

  describe('(package)', function() {
    describe('ReturnsV2Api', function() {
      describe('approveSelfShipReturns', function() {
        it('should call approveSelfShipReturns successfully', function(done) {
          // TODO: uncomment, update parameter values for approveSelfShipReturns call and complete the assertions
          /*
          var opts = {};

          instance.approveSelfShipReturns(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.ReturnsActionResponseV2);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cancelSelfShipReturn', function() {
        it('should call cancelSelfShipReturn successfully', function(done) {
          // TODO: uncomment, update parameter values for cancelSelfShipReturn call and complete the assertions
          /*
          var opts = {};

          instance.cancelSelfShipReturn(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.ReturnsActionResponseV2);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getReturns', function() {
        it('should call getReturns successfully', function(done) {
          // TODO: uncomment, update parameter values for getReturns call and complete the assertions
          /*
          var opts = {};

          instance.getReturns(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.ReturnsSearchResponseV2);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('pickup', function() {
        it('should call pickup successfully', function(done) {
          // TODO: uncomment, update parameter values for pickup call and complete the assertions
          /*
          var opts = {};

          instance.pickup(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.ReturnsActionResponseV2);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('pickupAttempt', function() {
        it('should call pickupAttempt successfully', function(done) {
          // TODO: uncomment, update parameter values for pickupAttempt call and complete the assertions
          /*
          var opts = {};

          instance.pickupAttempt(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.ReturnsActionResponseV2);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('rejectSelfShipReturns', function() {
        it('should call rejectSelfShipReturns successfully', function(done) {
          // TODO: uncomment, update parameter values for rejectSelfShipReturns call and complete the assertions
          /*
          var opts = {};

          instance.rejectSelfShipReturns(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.ReturnsActionResponseV2);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('returnComplete', function() {
        it('should call returnComplete successfully', function(done) {
          // TODO: uncomment, update parameter values for returnComplete call and complete the assertions
          /*
          var opts = {};

          instance.returnComplete(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.ReturnsActionResponseV2);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
