/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FlipkartMarketplaceApi);
  }
}(this, function(expect, FlipkartMarketplaceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FlipkartMarketplaceApi.SelfServeApi();
  });

  describe('(package)', function() {
    describe('SelfServeApi', function() {
      describe('changeDispatchSlots', function() {
        it('should call changeDispatchSlots successfully', function(done) {
          // TODO: uncomment, update parameter values for changeDispatchSlots call and complete the assertions
          /*

          instance.changeDispatchSlots(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.CreateCourierReturnResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createReturn', function() {
        it('should call createReturn successfully', function(done) {
          // TODO: uncomment, update parameter values for createReturn call and complete the assertions
          /*

          instance.createReturn(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.CreateCourierReturnResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createService', function() {
        it('should call createService successfully', function(done) {
          // TODO: uncomment, update parameter values for createService call and complete the assertions
          /*

          instance.createService(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.CreateCourierReturnResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createTestOrders', function() {
        it('should call createTestOrders successfully', function(done) {
          // TODO: uncomment, update parameter values for createTestOrders call and complete the assertions
          /*

          instance.createTestOrders(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.CreateTestOrdersResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('makeOrderUnHold', function() {
        it('should call makeOrderUnHold successfully', function(done) {
          // TODO: uncomment, update parameter values for makeOrderUnHold call and complete the assertions
          /*

          instance.makeOrderUnHold(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.CreateCourierReturnResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('markOrderItemDelivered', function() {
        it('should call markOrderItemDelivered successfully', function(done) {
          // TODO: uncomment, update parameter values for markOrderItemDelivered call and complete the assertions
          /*

          instance.markOrderItemDelivered(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.CreateCourierReturnResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('markOrderItemPickupComplete', function() {
        it('should call markOrderItemPickupComplete successfully', function(done) {
          // TODO: uncomment, update parameter values for markOrderItemPickupComplete call and complete the assertions
          /*

          instance.markOrderItemPickupComplete(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.CreateCourierReturnResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('markOrderItemShipped', function() {
        it('should call markOrderItemShipped successfully', function(done) {
          // TODO: uncomment, update parameter values for markOrderItemShipped call and complete the assertions
          /*

          instance.markOrderItemShipped(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.CreateCourierReturnResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('processReturnEvents', function() {
        it('should call processReturnEvents successfully', function(done) {
          // TODO: uncomment, update parameter values for processReturnEvents call and complete the assertions
          /*

          instance.processReturnEvents(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.CreateCourierReturnResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putOrderOnHold', function() {
        it('should call putOrderOnHold successfully', function(done) {
          // TODO: uncomment, update parameter values for putOrderOnHold call and complete the assertions
          /*

          instance.putOrderOnHold(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FlipkartMarketplaceApi.CreateCourierReturnResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
